[2022-09-01 18:08:16,758] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: trigger_sensor.process_results.sensor_triggered_dag manual__2022-09-01T18:08:12.552561+00:00 [queued]>
[2022-09-01 18:08:16,774] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: trigger_sensor.process_results.sensor_triggered_dag manual__2022-09-01T18:08:12.552561+00:00 [queued]>
[2022-09-01 18:08:16,775] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-01 18:08:16,775] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-09-01 18:08:16,776] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-01 18:08:16,809] {taskinstance.py:1397} INFO - Executing <Task(ExternalTaskSensor): process_results.sensor_triggered_dag> on 2022-09-01 18:08:12.552561+00:00
[2022-09-01 18:08:16,817] {standard_task_runner.py:52} INFO - Started process 88839 to run task
[2022-09-01 18:08:16,826] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'trigger_sensor', 'process_results.sensor_triggered_dag', 'manual__2022-09-01T18:08:12.552561+00:00', '--job-id', '3471', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmpsri56vwx', '--error-file', '/tmp/tmpve7aoedk']
[2022-09-01 18:08:16,828] {standard_task_runner.py:80} INFO - Job 3471: Subtask process_results.sensor_triggered_dag
[2022-09-01 18:08:16,932] {task_command.py:371} INFO - Running <TaskInstance: trigger_sensor.process_results.sensor_triggered_dag manual__2022-09-01T18:08:12.552561+00:00 [running]> on host 9d5d2a77e6ba
[2022-09-01 18:08:17,062] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_sensor
AIRFLOW_CTX_TASK_ID=process_results.sensor_triggered_dag
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T18:08:12.552561+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-01T18:08:12.552561+00:00
[2022-09-01 18:08:17,087] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 277, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/external_task.py", line 182, in poke
    serialized_dttm_filter = ','.join(dt.isoformat() for dt in dttm_filter)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/external_task.py", line 182, in <genexpr>
    serialized_dttm_filter = ','.join(dt.isoformat() for dt in dttm_filter)
AttributeError: 'NoneType' object has no attribute 'isoformat'
[2022-09-01 18:08:17,103] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=trigger_sensor, task_id=process_results.sensor_triggered_dag, execution_date=20220901T180812, start_date=20220901T180816, end_date=20220901T180817
[2022-09-01 18:08:17,125] {standard_task_runner.py:97} ERROR - Failed to execute job 3471 for task process_results.sensor_triggered_dag ('NoneType' object has no attribute 'isoformat'; 88839)
[2022-09-01 18:08:17,157] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-01 18:08:17,246] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
