[2022-09-07 22:17:53,924] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tables_name_1.create_table manual__2022-09-07T22:17:48.876841+00:00 [queued]>
[2022-09-07 22:17:53,940] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tables_name_1.create_table manual__2022-09-07T22:17:48.876841+00:00 [queued]>
[2022-09-07 22:17:53,942] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-07 22:17:53,943] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-09-07 22:17:53,944] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-07 22:17:53,964] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): create_table> on 2022-09-07 22:17:48.876841+00:00
[2022-09-07 22:17:53,970] {standard_task_runner.py:52} INFO - Started process 1297 to run task
[2022-09-07 22:17:53,977] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tables_name_1', 'create_table', 'manual__2022-09-07T22:17:48.876841+00:00', '--job-id', '3985', '--raw', '--subdir', 'DAGS_FOLDER/jobs_dag.py', '--cfg-path', '/tmp/tmpxq2cwini', '--error-file', '/tmp/tmpc5j_4_1z']
[2022-09-07 22:17:53,979] {standard_task_runner.py:80} INFO - Job 3985: Subtask create_table
[2022-09-07 22:17:54,073] {task_command.py:371} INFO - Running <TaskInstance: tables_name_1.create_table manual__2022-09-07T22:17:48.876841+00:00 [running]> on host e231cd7bc107
[2022-09-07 22:17:54,174] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tables_name_1
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-07T22:17:48.876841+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-07T22:17:48.876841+00:00
[2022-09-07 22:17:54,189] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-09-07 22:17:54,194] {dbapi.py:231} INFO - Running statement: -- create table
CREATE TABLE pg_catalog.my_table(custom_id integer NOT NULL, user_name VARCHAR (50) NOT NULL, timestamp TIMESTAMP NOT NULL);, parameters: None
[2022-09-07 22:17:54,201] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 235, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InsufficientPrivilege: permission denied to create "pg_catalog.my_table"
DETAIL:  System catalog modifications are currently disallowed.

[2022-09-07 22:17:54,215] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=tables_name_1, task_id=create_table, execution_date=20220907T221748, start_date=20220907T221753, end_date=20220907T221754
[2022-09-07 22:17:54,229] {standard_task_runner.py:97} ERROR - Failed to execute job 3985 for task create_table (permission denied to create "pg_catalog.my_table"
DETAIL:  System catalog modifications are currently disallowed.
; 1297)
[2022-09-07 22:17:54,270] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-07 22:17:54,323] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
