[2022-08-26 16:43:09,540] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: trigger_sensor.waiting_for_run_file manual__2022-08-26T16:43:08.710048+00:00 [queued]>
[2022-08-26 16:43:09,553] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: trigger_sensor.waiting_for_run_file manual__2022-08-26T16:43:08.710048+00:00 [queued]>
[2022-08-26 16:43:09,604] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-26 16:43:09,606] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-26 16:43:09,612] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-26 16:43:09,636] {taskinstance.py:1397} INFO - Executing <Task(FileSensor): waiting_for_run_file> on 2022-08-26 16:43:08.710048+00:00
[2022-08-26 16:43:09,645] {standard_task_runner.py:52} INFO - Started process 19542 to run task
[2022-08-26 16:43:09,651] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'trigger_sensor', 'waiting_for_run_file', 'manual__2022-08-26T16:43:08.710048+00:00', '--job-id', '3279', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmp2b2se9lw', '--error-file', '/tmp/tmpuzhb5e2s']
[2022-08-26 16:43:09,652] {standard_task_runner.py:80} INFO - Job 3279: Subtask waiting_for_run_file
[2022-08-26 16:43:09,755] {task_command.py:371} INFO - Running <TaskInstance: trigger_sensor.waiting_for_run_file manual__2022-08-26T16:43:08.710048+00:00 [running]> on host 9d5d2a77e6ba
[2022-08-26 16:43:09,870] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_sensor
AIRFLOW_CTX_TASK_ID=waiting_for_run_file
AIRFLOW_CTX_EXECUTION_DATE=2022-08-26T16:43:08.710048+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-26T16:43:08.710048+00:00
[2022-08-26 16:43:09,889] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:43:09,891] {filesystem.py:58} INFO - Poking for file test.txt
[2022-08-26 16:43:19,882] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:43:19,884] {filesystem.py:58} INFO - Poking for file test.txt
[2022-08-26 16:43:29,908] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:43:29,909] {filesystem.py:58} INFO - Poking for file test.txt
[2022-08-26 16:43:39,922] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:43:39,923] {filesystem.py:58} INFO - Poking for file test.txt
[2022-08-26 16:43:49,924] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:43:49,925] {filesystem.py:58} INFO - Poking for file test.txt
[2022-08-26 16:43:59,944] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:43:59,945] {filesystem.py:58} INFO - Poking for file test.txt
[2022-08-26 16:44:09,963] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:44:09,965] {filesystem.py:58} INFO - Poking for file test.txt
[2022-08-26 16:44:10,352] {local_task_job.py:221} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-08-26 16:44:10,367] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 19542. PIDs of all processes in the group: [19542]
[2022-08-26 16:44:10,369] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 19542
[2022-08-26 16:44:10,371] {taskinstance.py:1561} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-08-26 16:44:10,426] {process_utils.py:75} INFO - Process psutil.Process(pid=19542, status='terminated', exitcode=0, started='16:43:08') (19542) terminated with exit code 0
