[2022-08-17 15:45:32,279] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: my_dag.choose_best_model manual__2022-08-17T15:44:58+00:00 [queued]>
[2022-08-17 15:45:32,341] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: my_dag.choose_best_model manual__2022-08-17T15:44:58+00:00 [queued]>
[2022-08-17 15:45:32,342] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 15:45:32,343] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-17 15:45:32,343] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 15:45:32,372] {taskinstance.py:1397} INFO - Executing <Task(BranchPythonOperator): choose_best_model> on 2022-08-17 15:44:58+00:00
[2022-08-17 15:45:32,383] {standard_task_runner.py:52} INFO - Started process 2978 to run task
[2022-08-17 15:45:32,392] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'choose_best_model', 'manual__2022-08-17T15:44:58+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmppe26vjb4', '--error-file', '/tmp/tmpvmzdfodm']
[2022-08-17 15:45:32,393] {standard_task_runner.py:80} INFO - Job 77: Subtask choose_best_model
[2022-08-17 15:45:32,523] {task_command.py:371} INFO - Running <TaskInstance: my_dag.choose_best_model manual__2022-08-17T15:44:58+00:00 [running]> on host 9d5d2a77e6ba
[2022-08-17 15:45:32,677] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=choose_best_model
AIRFLOW_CTX_EXECUTION_DATE=2022-08-17T15:44:58+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-17T15:44:58+00:00
[2022-08-17 15:45:32,698] {python.py:173} INFO - Done. Returned value was: innacurate
[2022-08-17 15:45:32,725] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 221, in execute
    f"Branch callable must return valid task_ids. Invalid tasks found: {invalid_task_ids}"
airflow.exceptions.AirflowException: Branch callable must return valid task_ids. Invalid tasks found: {'innacurate'}
[2022-08-17 15:45:32,737] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=my_dag, task_id=choose_best_model, execution_date=20220817T154458, start_date=20220817T154532, end_date=20220817T154532
[2022-08-17 15:45:32,758] {standard_task_runner.py:97} ERROR - Failed to execute job 77 for task choose_best_model (Branch callable must return valid task_ids. Invalid tasks found: {'innacurate'}; 2978)
[2022-08-17 15:45:32,802] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-17 15:45:32,917] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
