[2022-09-01 18:17:07,317] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: trigger_sensor.process_results.sensor_triggered_dag manual__2022-09-01T18:17:03.234702+00:00 [queued]>
[2022-09-01 18:17:07,330] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: trigger_sensor.process_results.sensor_triggered_dag manual__2022-09-01T18:17:03.234702+00:00 [queued]>
[2022-09-01 18:17:07,331] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-01 18:17:07,331] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-09-01 18:17:07,332] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-01 18:17:07,350] {taskinstance.py:1397} INFO - Executing <Task(ExternalTaskSensor): process_results.sensor_triggered_dag> on 2022-09-01 18:17:03.234702+00:00
[2022-09-01 18:17:07,357] {standard_task_runner.py:52} INFO - Started process 89294 to run task
[2022-09-01 18:17:07,361] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'trigger_sensor', 'process_results.sensor_triggered_dag', 'manual__2022-09-01T18:17:03.234702+00:00', '--job-id', '3498', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmpsx4qmtzn', '--error-file', '/tmp/tmp99f4c0oy']
[2022-09-01 18:17:07,362] {standard_task_runner.py:80} INFO - Job 3498: Subtask process_results.sensor_triggered_dag
[2022-09-01 18:17:07,446] {task_command.py:371} INFO - Running <TaskInstance: trigger_sensor.process_results.sensor_triggered_dag manual__2022-09-01T18:17:03.234702+00:00 [running]> on host 9d5d2a77e6ba
[2022-09-01 18:17:07,538] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_sensor
AIRFLOW_CTX_TASK_ID=process_results.sensor_triggered_dag
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T18:17:03.234702+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-01T18:17:03.234702+00:00
[2022-09-01 18:17:07,540] {external_task.py:188} INFO - Poking for tasks None in dag dynamically_branching1 on 2022-09-01T18:17:03.234702+00:00 ... 
[2022-09-01 18:18:07,566] {external_task.py:188} INFO - Poking for tasks None in dag dynamically_branching1 on 2022-09-01T18:17:03.234702+00:00 ... 
[2022-09-01 18:19:07,536] {external_task.py:188} INFO - Poking for tasks None in dag dynamically_branching1 on 2022-09-01T18:17:03.234702+00:00 ... 
[2022-09-01 18:44:44,170] {external_task.py:188} INFO - Poking for tasks None in dag dynamically_branching1 on 2022-09-01T18:17:03.234702+00:00 ... 
[2022-09-01 18:44:45,356] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 288, in execute
    raise AirflowSensorTimeout(f"Snap. Time is OUT. DAG id: {log_dag_id}")
airflow.exceptions.AirflowSensorTimeout: Snap. Time is OUT. DAG id: trigger_sensor
[2022-09-01 18:44:45,407] {taskinstance.py:1420} INFO - Immediate failure requested. Marking task as FAILED. dag_id=trigger_sensor, task_id=process_results.sensor_triggered_dag, execution_date=20220901T181703, start_date=20220901T181707, end_date=20220901T184445
[2022-09-01 18:44:45,459] {standard_task_runner.py:97} ERROR - Failed to execute job 3498 for task process_results.sensor_triggered_dag (Snap. Time is OUT. DAG id: trigger_sensor; 89294)
[2022-09-01 18:44:45,509] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-01 18:44:45,582] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
