[2022-09-01 17:57:20,722] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: trigger_sensor.process_results.sensor_triggered_dag manual__2022-09-01T17:56:57.353439+00:00 [queued]>
[2022-09-01 17:57:20,734] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: trigger_sensor.process_results.sensor_triggered_dag manual__2022-09-01T17:56:57.353439+00:00 [queued]>
[2022-09-01 17:57:20,735] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-01 17:57:20,736] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-09-01 17:57:20,737] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-01 17:57:20,756] {taskinstance.py:1397} INFO - Executing <Task(ExternalTaskSensor): process_results.sensor_triggered_dag> on 2022-09-01 17:56:57.353439+00:00
[2022-09-01 17:57:20,763] {standard_task_runner.py:52} INFO - Started process 88312 to run task
[2022-09-01 17:57:20,767] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'trigger_sensor', 'process_results.sensor_triggered_dag', 'manual__2022-09-01T17:56:57.353439+00:00', '--job-id', '3459', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmpvhdaiyvk', '--error-file', '/tmp/tmp5730vtyw']
[2022-09-01 17:57:20,768] {standard_task_runner.py:80} INFO - Job 3459: Subtask process_results.sensor_triggered_dag
[2022-09-01 17:57:20,863] {task_command.py:371} INFO - Running <TaskInstance: trigger_sensor.process_results.sensor_triggered_dag manual__2022-09-01T17:56:57.353439+00:00 [running]> on host 9d5d2a77e6ba
[2022-09-01 17:57:20,957] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_sensor
AIRFLOW_CTX_TASK_ID=process_results.sensor_triggered_dag
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T17:56:57.353439+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-01T17:56:57.353439+00:00
[2022-09-01 17:57:20,978] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 277, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/external_task.py", line 182, in poke
    serialized_dttm_filter = ','.join(dt.isoformat() for dt in dttm_filter)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/external_task.py", line 182, in <genexpr>
    serialized_dttm_filter = ','.join(dt.isoformat() for dt in dttm_filter)
AttributeError: 'NoneType' object has no attribute 'isoformat'
[2022-09-01 17:57:20,990] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=trigger_sensor, task_id=process_results.sensor_triggered_dag, execution_date=20220901T175657, start_date=20220901T175720, end_date=20220901T175720
[2022-09-01 17:57:21,005] {standard_task_runner.py:97} ERROR - Failed to execute job 3459 for task process_results.sensor_triggered_dag ('NoneType' object has no attribute 'isoformat'; 88312)
[2022-09-01 17:57:21,020] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-01 17:57:21,088] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
