[2022-08-26 16:39:07,703] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: trigger_sensor.waiting_for_run_file manual__2022-08-26T16:39:06.383622+00:00 [queued]>
[2022-08-26 16:39:07,715] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: trigger_sensor.waiting_for_run_file manual__2022-08-26T16:39:06.383622+00:00 [queued]>
[2022-08-26 16:39:07,716] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-26 16:39:07,717] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-26 16:39:07,718] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-26 16:39:07,736] {taskinstance.py:1397} INFO - Executing <Task(FileSensor): waiting_for_run_file> on 2022-08-26 16:39:06.383622+00:00
[2022-08-26 16:39:07,743] {standard_task_runner.py:52} INFO - Started process 19355 to run task
[2022-08-26 16:39:07,747] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'trigger_sensor', 'waiting_for_run_file', 'manual__2022-08-26T16:39:06.383622+00:00', '--job-id', '3277', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmpwp00judh', '--error-file', '/tmp/tmpwyc7qbma']
[2022-08-26 16:39:07,749] {standard_task_runner.py:80} INFO - Job 3277: Subtask waiting_for_run_file
[2022-08-26 16:39:07,840] {task_command.py:371} INFO - Running <TaskInstance: trigger_sensor.waiting_for_run_file manual__2022-08-26T16:39:06.383622+00:00 [running]> on host 9d5d2a77e6ba
[2022-08-26 16:39:07,942] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_sensor
AIRFLOW_CTX_TASK_ID=waiting_for_run_file
AIRFLOW_CTX_EXECUTION_DATE=2022-08-26T16:39:06.383622+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-26T16:39:06.383622+00:00
[2022-08-26 16:39:07,954] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:39:07,955] {filesystem.py:58} INFO - Poking for file /opt/***/Test/test.txt
[2022-08-26 16:39:17,953] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:39:17,954] {filesystem.py:58} INFO - Poking for file /opt/***/Test/test.txt
[2022-08-26 16:39:27,975] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:39:27,976] {filesystem.py:58} INFO - Poking for file /opt/***/Test/test.txt
[2022-08-26 16:39:37,998] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:39:38,000] {filesystem.py:58} INFO - Poking for file /opt/***/Test/test.txt
[2022-08-26 16:39:48,001] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:39:48,002] {filesystem.py:58} INFO - Poking for file /opt/***/Test/test.txt
[2022-08-26 16:39:58,018] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:39:58,019] {filesystem.py:58} INFO - Poking for file /opt/***/Test/test.txt
[2022-08-26 16:40:08,035] {base.py:68} INFO - Using connection ID 'my_file_system_practice' for task execution.
[2022-08-26 16:40:08,036] {filesystem.py:58} INFO - Poking for file /opt/***/Test/test.txt
[2022-08-26 16:40:08,037] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 288, in execute
    raise AirflowSensorTimeout(f"Snap. Time is OUT. DAG id: {log_dag_id}")
airflow.exceptions.AirflowSensorTimeout: Snap. Time is OUT. DAG id: trigger_sensor
[2022-08-26 16:40:08,050] {taskinstance.py:1420} INFO - Immediate failure requested. Marking task as FAILED. dag_id=trigger_sensor, task_id=waiting_for_run_file, execution_date=20220826T163906, start_date=20220826T163907, end_date=20220826T164008
[2022-08-26 16:40:08,073] {standard_task_runner.py:97} ERROR - Failed to execute job 3277 for task waiting_for_run_file (Snap. Time is OUT. DAG id: trigger_sensor; 19355)
[2022-08-26 16:40:08,113] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-26 16:40:08,176] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
