[2022-08-30 18:21:15,657] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dynamically_branching1.query_table manual__2022-08-26T19:30:57.905498+00:00 [queued]>
[2022-08-30 18:21:15,742] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dynamically_branching1.query_table manual__2022-08-26T19:30:57.905498+00:00 [queued]>
[2022-08-30 18:21:15,743] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-30 18:21:15,744] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-30 18:21:15,745] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-30 18:21:15,863] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): query_table> on 2022-08-26 19:30:57.905498+00:00
[2022-08-30 18:21:15,875] {standard_task_runner.py:52} INFO - Started process 75765 to run task
[2022-08-30 18:21:15,914] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dynamically_branching1', 'query_table', 'manual__2022-08-26T19:30:57.905498+00:00', '--job-id', '3364', '--raw', '--subdir', 'DAGS_FOLDER/jobs_dag.py', '--cfg-path', '/tmp/tmpv249x78d', '--error-file', '/tmp/tmphk9l3o1b']
[2022-08-30 18:21:15,915] {standard_task_runner.py:80} INFO - Job 3364: Subtask query_table
[2022-08-30 18:21:16,179] {task_command.py:371} INFO - Running <TaskInstance: dynamically_branching1.query_table manual__2022-08-26T19:30:57.905498+00:00 [running]> on host 9d5d2a77e6ba
[2022-08-30 18:21:16,519] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dynamically_branching1
AIRFLOW_CTX_TASK_ID=query_table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-26T19:30:57.905498+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-26T19:30:57.905498+00:00
[2022-08-30 18:21:16,525] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/jobs_dag.py", line 39, in xcom_call
    ti.xcom_push(key='ended_id',value={{'run_id'}})
TypeError: unhashable type: 'set'
[2022-08-30 18:21:16,566] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dynamically_branching1, task_id=query_table, execution_date=20220826T193057, start_date=20220830T182115, end_date=20220830T182116
[2022-08-30 18:21:16,714] {standard_task_runner.py:97} ERROR - Failed to execute job 3364 for task query_table (unhashable type: 'set'; 75765)
[2022-08-30 18:21:16,810] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-30 18:21:17,073] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
